postgres:
  image: postgres:9.5
  ports:
    - "5432"
  volumes:
  - /var/lib/postgresql/data


redis:
  image: redis:3
  restart: always
  ports:
    - "6379:6379"

mysql:
  image: mysql
  restart: always
  ports:
      - '3306:3306'
  volumes:
    - '/opt/mysql:/var/lib/mysql'
  environment:
    - MYSQL_DATABASE=mysitedb
    - MYSQL_ROOT_PASSWORD: '123456'
  
  
# https://hub.docker.com/_/zookeeper/
zookeeper:
  image: zookeeper:3.4.9
  restart: always
  ports:
    - '2181:2181'
    - '2888:2888'
    - '3888:3888'    
  environment:
    ZOO_MY_ID: 1
    #ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
